Repository jdu211171/jduportfolio, pull requests merged in 2025-04, with the labels that each got.

#72 Enhance ProfileConfirmDialog with improved content structure, added d…
  portfolio-client/src/components/Dialogs/ProfileConfirmDialog.jsx
Labels: documentation, enhancement

#75 Enhance Filter component with autocomplete suggestions and debounce i…
  portfolio-client/package.json
  portfolio-client/src/components/Filter/Filter.jsx
Labels: enhancement

#77 76-remove-user-avatar-from-notification
  portfolio-client/src/components/Notification/Notifications.jsx
  portfolio-client/src/components/Notification/Notifications.module.css
Labels: bug, enhancement

#81 Refactor Table component to include reusable pagination controls; enhance layout with top and bottom pagination sections
  portfolio-client/package.json
  portfolio-client/src/components/Table/Table.jsx
Labels: bug

#85 Image branch
  portfolio-server/migrations/20250219191610-create-image.js
  portfolio-server/migrations/20250219191611-update-drafts-status-enum.js
  portfolio-server/package.json
  portfolio-server/src/app.js
  portfolio-server/src/models/Image.js
  portfolio-server/src/routes/image-routes.js
  portfolio-server/src/services/s3.js
Labels: enhancement

#101 Add onClick handler to search input for improved functionality
  portfolio-client/src/components/Filter/Filter.jsx
Labels: enhancement
